// ===== dt-sim.js - Decision tree simulation, node CRUD, and model helpers =====
// Split from decision-tree.js. Pure model/simulation layer.

import {
  gridLevels, insightLvs, insightProgress, magData, magnifiersOwned,
  occFound, researchLevel, shapeOverlay, shapePositions,
} from '../state.js';
import {
  OCC_DATA, RES_GRID_RAW, SHAPE_NAMES, SHAPE_COLORS,
} from '../game-data.js';
import {
  advanceInsightLevels, advanceResearchLevel,
  computeOccurrencesToBeFound, getMonoObsSet,
  hrsToNextInsightLv, magMaxForLevel, researchExpReq, simTotalExpWith,
} from '../sim-math.js';
import { getResearchCurrentExp, makeCtx } from '../save/context.js';
import { chooseMonoTargets } from '../optimizers/monos.js';
import {
  _dtNodes, _dtCompareSet, DT,
  _dtGetNode, _dtGetChildren,
  _dtCloneState, _dtGridPointsAvail,
} from './dt-state.js';


// Build initial state from current globals
export function _dtBuildInitState() {
  const rLv = researchLevel;
  const gl = gridLevels.slice();
  const so = shapeOverlay.slice();
  const md = magData.slice(0, magnifiersOwned).map(m => ({...m}));
  const il = insightLvs.slice();
  const ip = insightProgress.slice();
  const occ = occFound.slice();
  const sp = shapePositions.map(s => ({...s}));
  const ctx = makeCtx(gl);
  const expHr = simTotalExpWith(gl, so, md, il, occ, rLv, ctx);
  return {
    gl, so, md, il, ip, occ, sp, rLv, rExp: getResearchCurrentExp(), expHr
  };
}

// Create a node and add to tree
export function _dtCreateNode(parentId, event, time, state) {
  const node = {
    id: DT.nextId++,
    parentId,
    childIds: [],
    event,             // 'start' | 'level-up' | 'insight-up' | 'level+insight'
    time,              // cumulative hours from root of this node's branch
    rLv: state.rLv,
    rExp: state.rExp,
    expHr: state.expHr,
    baseState: _dtCloneState(state),
    autoInsight: false,         // user toggle: auto-optimize insight until next research level-up
    _autoInsightChild: false,   // auto-generated by parent's autoInsight chain
    insightTimeline: null,      // [{time, obs, prevIL, newIL, monoTargets}] on the final level-up node
    insightObs: null,           // [obsIdx, ...] which obs had insight level up (for insight-up/level+insight events)
    insightLvs: null,           // {obsIdx: newLv, ...} new insight levels for leveled-up obs
    _x: 0, _y: 0, _depth: 0,
    _branchIdx: 0,
  };
  _dtNodes.push(node);
  if (parentId !== null) {
    const parent = _dtGetNode(parentId);
    if (parent) parent.childIds.push(node.id);
  }
  return node;
}

// Step sim: run from a state to the next event, return event info + new state
export function _dtStepSim(state) {
  let gl = state.gl.slice();
  let so = state.so.slice();
  let md = state.md.map(m => ({...m}));
  let il = state.il.slice();
  let ip = state.ip.slice();
  let occ = state.occ.slice();
  let rLv = state.rLv;
  let rExp = state.rExp;
  const ctx = makeCtx(gl);
  let curExpHr = simTotalExpWith(gl, so, md, il, occ, rLv, ctx);
  let currentTime = 0;

  for (let jump = 0; jump < 50000; jump++) {
    if (curExpHr <= 0) return null;

    // Time to next research level-up
    const expToLv = researchExpReq(rLv, ctx.serverVarResXP) - rExp;
    let jumpHrs = expToLv / curExpHr;

    // Time to next insight level-up
    const monoObs = getMonoObsSet(md);
    const hrsToIns = hrsToNextInsightLv(monoObs, md, il, ip, gl, so, ctx);
    if (hrsToIns < jumpHrs) jumpHrs = hrsToIns;
    if (jumpHrs <= 0) jumpHrs = 1e-9;
    if (jumpHrs > 1e8) return null;

    const jumpSec = jumpHrs * 3600;
    rExp += curExpHr / 3600 * jumpSec;
    currentTime += jumpHrs;

    // Advance insight
    const insightLeveledObs = [];
    const insightLeveledLvs = {};
    let insightLeveledUp = advanceInsightLevels(monoObs, md, il, ip, gl, so, ctx, jumpHrs, (obsIdx) => {
      insightLeveledObs.push(obsIdx);
      insightLeveledLvs[obsIdx] = il[obsIdx];
    });

    // Check level-ups
    var _adv = advanceResearchLevel(rExp, rLv, ctx.serverVarResXP);
    rExp = _adv.rExp; rLv = _adv.rLv; var rLeveledUp = _adv.changed;

    // Auto-unlock obs
    if (rLeveledUp) {
      for (let oi = 0; oi < OCC_DATA.length; oi++) {
        if ((occ[oi] || 0) < 1 && OCC_DATA[oi].roll <= rLv) occ[oi] = 1;
      }
    }

    if (rLeveledUp || insightLeveledUp) {
      curExpHr = simTotalExpWith(gl, so, md, il, occ, rLv, ctx);
      const eventType = rLeveledUp && insightLeveledUp ? 'level+insight'
        : rLeveledUp ? 'level-up' : 'insight-up';
      return {
        event: eventType,
        time: currentTime,
        insightObs: insightLeveledObs.length > 0 ? insightLeveledObs : null,
        insightLvs: Object.keys(insightLeveledLvs).length > 0 ? insightLeveledLvs : null,
        state: { gl, so, md, il, ip, occ, sp: state.sp.map(s => ({...s})), rLv, rExp, expHr: curExpHr }
      };
    }
  }
  return null;
}

// Auto-advance through insight level-ups, applying monocle reopt at each,
// until we hit a research level-up (or level+insight).
export function _dtAdvanceAutoInsight(parentNode) {
  const timeline = [];
  let curParentId = parentNode.id;
  let cumTime = 0;
  let curState = _dtCloneState({...parentNode.baseState, rLv: parentNode.rLv, rExp: parentNode.rExp, expHr: parentNode.expHr});

  for (let safety = 0; safety < 500; safety++) {
    const result = _dtStepSim(curState);
    if (!result) return null;

    cumTime += result.time;

    if (result.event === 'level-up' || result.event === 'level+insight') {
      const finalNode = _dtCreateNode(curParentId, result.event, result.time, result.state);
      finalNode.insightTimeline = timeline.length > 0 ? timeline : null;
      finalNode.insightObs = result.insightObs;
      finalNode.insightLvs = result.insightLvs;
      finalNode.autoInsight = true;
      return finalNode;
    }

    // insight-up: create hidden intermediate, apply monocle reopt, continue
    const mMax = magMaxForLevel(result.state.rLv);

    const insightChanges = [];
    for (let i = 0; i < result.state.il.length; i++) {
      const prev = curState.il[i] || 0;
      const now = result.state.il[i] || 0;
      if (now > prev) insightChanges.push({ obs: i, prevIL: prev, newIL: now });
    }

    result.state.md = chooseMonoTargets(
      {gl: result.state.gl, so: result.state.so, md: result.state.md, il: result.state.il, ip: result.state.ip, occ: result.state.occ, rLv: result.state.rLv, mMax},
      undefined, 72
    );
    const ctx = makeCtx(result.state.gl);
    result.state.expHr = simTotalExpWith(
      result.state.gl, result.state.so, result.state.md, result.state.il,
      result.state.occ, result.state.rLv, ctx
    );

    const monoTargets = [...getMonoObsSet(result.state.md)];

    for (const ic of insightChanges) {
      timeline.push({
        time: cumTime,
        obs: ic.obs,
        prevIL: ic.prevIL,
        newIL: ic.newIL,
        monoTargets: [...new Set(monoTargets)],
        expHr: result.state.expHr,
      });
    }

    const interNode = _dtCreateNode(curParentId, result.event, result.time, result.state);
    interNode.insightObs = result.insightObs;
    interNode.insightLvs = result.insightLvs;
    interNode._autoInsightChild = true;

    curParentId = interNode.id;
    curState = _dtCloneState(result.state);
  }
  return null;
}

// ===== VISIBILITY HELPERS =====
export function _dtIsNodeVisible(node) {
  if (node._autoInsightChild) return false;
  if (!DT.showLevelUpsOnly) return true;
  return node.event !== 'insight-up';
}
export function _dtVisibleParent(node) {
  let cur = node.parentId !== null ? _dtGetNode(node.parentId) : null;
  while (cur && !_dtIsNodeVisible(cur)) cur = cur.parentId !== null ? _dtGetNode(cur.parentId) : null;
  return cur;
}
export function _dtVisibleChildren(nodeId) {
  const result = [];
  function collect(id) {
    for (const ch of _dtGetChildren(id)) {
      if (_dtIsNodeVisible(ch)) result.push(ch);
      else collect(ch.id);
    }
  }
  collect(nodeId);
  return result;
}

// Get cumulative time from root to a node
export function _dtGetTotalTime(node) {
  let total = 0;
  let cur = node;
  while (cur) {
    total += cur.time;
    cur = cur.parentId !== null ? _dtGetNode(cur.parentId) : null;
  }
  return total;
}

// Build compact change summary lines for a tree node card
export function _dtNodeChangeSummary(node) {
  if (!node || node.parentId === null) return [];
  const parent = _dtGetNode(node.parentId);
  if (!parent) return [];
  const lines = [];
  const pgl = parent.baseState.gl, ngl = node.baseState.gl;

  // Grid changes - show abbreviated upgrade names
  const gridParts = [];
  for (const idx of Object.keys(RES_GRID_RAW)) {
    const i = Number(idx);
    const pv = pgl[i] || 0, nv = ngl[i] || 0;
    if (nv !== pv) {
      let name = RES_GRID_RAW[i][0].replace(/_/g, ' ');
      if (name.length > 12) name = name.slice(0, 11) + '\u2026';
      gridParts.push(name + ' +' + (nv - pv));
    }
  }
  if (gridParts.length > 0) {
    let text = gridParts[0];
    for (let i = 1; i < gridParts.length; i++) {
      const next = text + ', ' + gridParts[i];
      if (next.length > 28) { text += ' +' + (gridParts.length - i) + ' more'; break; }
      text = next;
    }
    lines.push({ text, color: '#8cf' });
  }

  // Shape changes
  const psp = parent.baseState.sp, nsp = node.baseState.sp;
  const movedShapes = [];
  for (let i = 0; i < Math.max(psp.length, nsp.length); i++) {
    const ps = psp[i] || {}, ns = nsp[i] || {};
    if (ps.x !== ns.x || ps.y !== ns.y || ps.rot !== ns.rot) {
      movedShapes.push(SHAPE_NAMES?.[i] || ('S' + (i + 1)));
    }
  }
  if (movedShapes.length > 0) {
    let text = movedShapes.slice(0, 3).join(', ');
    if (movedShapes.length > 3) text += ' +' + (movedShapes.length - 3);
    lines.push({ text: '\u25C6 ' + text, color: '#c9a' });
  }

  // Mag changes
  const pmd = parent.baseState.md, nmd = node.baseState.md;
  let magDiffs = 0;
  const slotCheck = Math.max(pmd.length, nmd.length);
  for (let i = 0; i < slotCheck; i++) {
    const pm = pmd[i] || {}, nm = nmd[i] || {};
    if (pm.slot !== nm.slot || pm.type !== nm.type) magDiffs++;
  }
  if (magDiffs > 0) {
    lines.push({ text: '\uD83D\uDD2C ' + magDiffs + ' mag' + (magDiffs > 1 ? 's' : '') + ' changed', color: '#ad8' });
  }

  return lines;
}

// Compute changes between a node and its parent (for comparison panel)
export function _dtComputeChanges(node) {
  if (!node || node.parentId === null) return [];
  const parent = _dtGetNode(node.parentId);
  if (!parent) return [];
  const changes = [];
  const pgl = parent.baseState.gl, ngl = node.baseState.gl;
  const gridChanges = [];
  for (const idx of Object.keys(RES_GRID_RAW)) {
    const i = Number(idx);
    const pv = pgl[i] || 0, nv = ngl[i] || 0;
    if (nv !== pv) {
      const name = RES_GRID_RAW[i][0].replace(/_/g, ' ');
      gridChanges.push(`${name} ${pv}\u2192${nv}`);
    }
  }
  if (gridChanges.length > 0) changes.push('Grid: ' + gridChanges.join(', '));
  const magKey = (md) => {
    const m = {};
    for (const mag of md) { const k = mag.slot + ':' + mag.type; m[k] = (m[k]||0)+1; }
    return m;
  };
  const pmk = magKey(parent.baseState.md), nmk = magKey(node.baseState.md);
  const allMagKeys = new Set([...Object.keys(pmk), ...Object.keys(nmk)]);
  let magDiffs = 0;
  for (const k of allMagKeys) { if ((pmk[k]||0) !== (nmk[k]||0)) magDiffs++; }
  if (magDiffs > 0) changes.push(`Mags: ${magDiffs} change${magDiffs>1?'s':''}`);
  const psp = parent.baseState.sp, nsp = node.baseState.sp;
  let shapeDiffs = 0;
  for (let i = 0; i < Math.max(psp.length, nsp.length); i++) {
    const ps = psp[i] || {}, ns = nsp[i] || {};
    if (ps.x !== ns.x || ps.y !== ns.y || ps.rot !== ns.rot) shapeDiffs++;
  }
  if (shapeDiffs > 0) changes.push(`Shapes: ${shapeDiffs} moved`);
  return changes;
}

// ===== RE-SIM DOWNSTREAM =====
export function _dtResimChildrenOf(parentNode) {
  const origChildIds = parentNode.childIds.slice();
  for (const childId of origChildIds) {
    const child = _dtGetNode(childId);
    if (!child) continue;

    if (child._autoInsightChild) {
      const chainIds = [];
      let cur = child;
      while (cur && cur._autoInsightChild) {
        chainIds.push(cur.id);
        const kids = _dtGetChildren(cur.id);
        cur = kids.length > 0 ? kids[0] : null;
      }
      let savedChildIds = [];
      if (cur) {
        chainIds.push(cur.id);
        savedChildIds = cur.childIds.slice();
      }
      const chainSet = new Set(chainIds);
      for (const cid of chainIds) _dtCompareSet.delete(cid);
      parentNode.childIds = parentNode.childIds.filter(id => id !== childId);
      for (let i = _dtNodes.length - 1; i >= 0; i--) {
        if (chainSet.has(_dtNodes[i].id)) _dtNodes.splice(i, 1);
      }
      let newTail = null;
      if (parentNode.autoInsight) {
        newTail = _dtAdvanceAutoInsight(parentNode);
      } else {
        const ps = _dtCloneState({...parentNode.baseState, rLv: parentNode.rLv, rExp: parentNode.rExp, expHr: parentNode.expHr});
        const r = _dtStepSim(ps);
        if (r) {
          newTail = _dtCreateNode(parentNode.id, r.event, r.time, r.state);
          newTail.insightObs = r.insightObs;
          newTail.insightLvs = r.insightLvs;
        }
      }
      if (newTail && savedChildIds.length > 0) {
        for (const scId of savedChildIds) {
          const sc = _dtGetNode(scId);
          if (sc) sc.parentId = newTail.id;
        }
        newTail.childIds.push(...savedChildIds);
        _dtResimChildrenOf(newTail);
      } else if (!newTail && savedChildIds.length > 0) {
        for (const scId of savedChildIds) {
          const sc = _dtGetNode(scId);
          if (sc) sc.parentId = parentNode.id;
        }
        parentNode.childIds.push(...savedChildIds);
        for (const scId of savedChildIds) {
          const sc = _dtGetNode(scId);
          if (sc) _dtResimChildrenOf(sc);
        }
      }
      continue;
    }

    const parentState = _dtCloneState({...parentNode.baseState, rLv: parentNode.rLv, rExp: parentNode.rExp, expHr: parentNode.expHr});
    const result = _dtStepSim(parentState);
    if (result) {
      child.event = result.event;
      child.time = result.time;
      child.rLv = result.state.rLv;
      child.rExp = result.state.rExp;
      child.expHr = result.state.expHr;
      child.baseState = _dtCloneState(result.state);
      child.insightObs = result.insightObs;
      child.insightLvs = result.insightLvs;
    }
    _dtResimChildrenOf(child);
  }
}

// Rebuild insightTimeline on nodes by walking back through auto-insight ancestors
export function _dtRebuildInsightTimelines() {
  for (const node of _dtNodes) {
    if (node._autoInsightChild || !node.insightTimeline) continue;
    const chain = [];
    let cur = node;
    while (cur.parentId !== null) {
      const p = _dtGetNode(cur.parentId);
      if (p && p._autoInsightChild) { chain.unshift(p); cur = p; }
      else break;
    }
    if (chain.length === 0) { node.insightTimeline = null; continue; }
    const originParent = cur.parentId !== null ? _dtGetNode(cur.parentId) : null;
    let prevILArr = originParent ? originParent.baseState.il : [];
    const timeline = [];
    let cumT = 0;
    for (const cn of chain) {
      cumT += cn.time;
      for (let i = 0; i < cn.baseState.il.length; i++) {
        const prev = prevILArr[i] || 0;
        const now = cn.baseState.il[i] || 0;
        if (now > prev) {
          const monoTargets = [...getMonoObsSet(cn.baseState.md)];
          timeline.push({ time: cumT, obs: i, prevIL: prev, newIL: now, monoTargets, expHr: cn.expHr });
        }
      }
      prevILArr = cn.baseState.il;
    }
    node.insightTimeline = timeline.length > 0 ? timeline : null;
  }
}
