// ===== decision-tree.js - Interactive Decision Tree + renderAll orchestrator =====
//
// TABLE OF CONTENTS (after split)
//   dt-state.js  - Shared state, accessors, cloneState, gridPointsAvail
//   dt-grid.js   - Unified Grid + Shape Canvas, obs editor, grid tooltip
//   (this file)  - Sim stepping, tree layout, tree canvas, modal, save/compare/delete/reset/branch/start

import {
  gridLevels, insightLvs, insightProgress, magData, magnifiersOwned,
  occFound, researchLevel, shapeOverlay, shapePositions,
} from '../state.js';
import {
  OCC_DATA, RES_GRID_RAW, SHAPE_NAMES, SHAPE_COLORS,
} from '../game-data.js';
import {
  advanceInsightLevels, advanceResearchLevel, computeMagnifiersOwnedWith,
  computeOccurrencesToBeFound, computeShapesOwnedAt, getMonoObsSet,
  hrsToNextInsightLv, magMaxForLevel, researchExpReq, simTotalExpWith,
} from '../sim-math.js';
import { getResearchCurrentExp, makeCtx } from '../save/context.js';
import { optimizeMagsFor } from '../optimizers/magnifiers.js';
import { chooseMonoTargets } from '../optimizers/monos.js';
import { optimizeShapesFor } from '../sim-engine.js';
import { fmtTime, fmtVal } from './format.js';
import { renderDashboard } from '../ui/dashboard.js';
import {
  _dtNodes, _dtCompareSet, DT,
  _dtGetNode, _dtGetChildren, _dtGetRoot,
  _dtCloneState, _dtGridPointsAvail,
  _DT_COL_W, _DT_ROW_H, _DT_NODE_W, _DT_NODE_H, _DT_PAD, _DT_BRANCH_COLORS,
} from './dt-state.js';
import {
  _dtRecalcExpHr, _dtResetGridState, _dtSetGridMode, _dtSetShapeOpacity,
  _dtRenderGridCanvas, _dtRenderObsEditor, _dtRebuildOverlay,
} from './dt-grid.js';

// Re-export shared state for external consumers (app.js, state-io.js)
export { _dtNodes, _dtCompareSet, DT } from './dt-state.js';
export { _dtRenderGridCanvas, _dtSetGridMode, _dtSetShapeOpacity } from './dt-grid.js';

// Build initial state from current globals
function _dtBuildInitState() {
  const rLv = researchLevel;
  const gl = gridLevels.slice();
  const so = shapeOverlay.slice();
  const md = magData.slice(0, magnifiersOwned).map(m => ({...m}));
  const il = insightLvs.slice();
  const ip = insightProgress.slice();
  const occ = occFound.slice();
  const sp = shapePositions.map(s => ({...s}));
  const ctx = makeCtx(gl);
  const expHr = simTotalExpWith(gl, so, md, il, occ, rLv, ctx);
  return {
    gl, so, md, il, ip, occ, sp, rLv, rExp: getResearchCurrentExp(), expHr
  };
}

// Create a node and add to tree
function _dtCreateNode(parentId, event, time, state) {
  const node = {
    id: DT.nextId++,
    parentId,
    childIds: [],
    event,             // 'start' | 'level-up' | 'insight-up' | 'level+insight'
    time,              // cumulative hours from root of this node's branch
    rLv: state.rLv,
    rExp: state.rExp,
    expHr: state.expHr,
    baseState: _dtCloneState(state),
    autoInsight: false,         // user toggle: auto-optimize insight until next research level-up
    _autoInsightChild: false,   // auto-generated by parent's autoInsight chain
    insightTimeline: null,      // [{time, obs, prevIL, newIL, monoTargets}] on the final level-up node
    _x: 0, _y: 0, _depth: 0,
    _branchIdx: 0,
  };
  _dtNodes.push(node);
  if (parentId !== null) {
    const parent = _dtGetNode(parentId);
    if (parent) parent.childIds.push(node.id);
  }
  return node;
}

// Step sim: run from a state to the next event, return event info + new state
// Uses event-driven jumps instead of fixed ticks.
function _dtStepSim(state) {
  let gl = state.gl.slice();
  let so = state.so.slice();
  let md = state.md.map(m => ({...m}));
  let il = state.il.slice();
  let ip = state.ip.slice();
  let occ = state.occ.slice();
  let rLv = state.rLv;
  let rExp = state.rExp;
  const ctx = makeCtx(gl);
  let curExpHr = simTotalExpWith(gl, so, md, il, occ, rLv, ctx);
  let currentTime = 0;

  for (let jump = 0; jump < 50000; jump++) {
    if (curExpHr <= 0) return null;

    // Time to next research level-up
    const expToLv = researchExpReq(rLv) - rExp;
    let jumpHrs = expToLv / curExpHr;

    // Time to next insight level-up
    const monoObs = getMonoObsSet(md);
    const hrsToIns = hrsToNextInsightLv(monoObs, md, il, ip, gl, so, ctx);
    if (hrsToIns < jumpHrs) jumpHrs = hrsToIns;
    if (jumpHrs <= 0) jumpHrs = 1e-9;
    if (jumpHrs > 1e8) return null;

    const jumpSec = jumpHrs * 3600;
    rExp += curExpHr / 3600 * jumpSec;
    currentTime += jumpHrs;

    // Advance insight
    let insightLeveledUp = advanceInsightLevels(monoObs, md, il, ip, gl, so, ctx, jumpHrs);

    // Check level-ups
    var _adv = advanceResearchLevel(rExp, rLv);
    rExp = _adv.rExp; rLv = _adv.rLv; var rLeveledUp = _adv.changed;

    // Auto-unlock obs
    if (rLeveledUp) {
      for (let oi = 0; oi < OCC_DATA.length; oi++) {
        if ((occ[oi] || 0) < 1 && OCC_DATA[oi].roll <= rLv) occ[oi] = 1;
      }
    }

    if (rLeveledUp || insightLeveledUp) {
      curExpHr = simTotalExpWith(gl, so, md, il, occ, rLv, ctx);
      const eventType = rLeveledUp && insightLeveledUp ? 'level+insight'
        : rLeveledUp ? 'level-up' : 'insight-up';
      return {
        event: eventType,
        time: currentTime,
        state: { gl, so, md, il, ip, occ, sp: state.sp.map(s => ({...s})), rLv, rExp, expHr: curExpHr }
      };
    }
  }
  return null;
}

// Auto-advance through insight level-ups, applying monocle reopt at each,
// until we hit a research level-up (or level+insight). Creates intermediate
// hidden nodes and records a timeline of insight switches.
function _dtAdvanceAutoInsight(parentNode) {
  const timeline = [];
  let curParentId = parentNode.id;
  let cumTime = 0;
  let curState = _dtCloneState({...parentNode.baseState, rLv: parentNode.rLv, rExp: parentNode.rExp, expHr: parentNode.expHr});

  for (let safety = 0; safety < 500; safety++) {
    const result = _dtStepSim(curState);
    if (!result) return null; // sim didn't find any event

    cumTime += result.time;

    if (result.event === 'level-up' || result.event === 'level+insight') {
      // Final node - this is the one the user sees
      const finalNode = _dtCreateNode(curParentId, result.event, result.time, result.state);
      finalNode.insightTimeline = timeline.length > 0 ? timeline : null;
      finalNode.autoInsight = true; // propagate so next advance also auto-optimizes
      return finalNode;
    }

    // insight-up: create hidden intermediate, apply monocle reopt, continue
    const mMax = magMaxForLevel(result.state.rLv);

    // Figure out which obs leveled up (compare to curState before this step)
    const insightChanges = [];
    for (let i = 0; i < result.state.il.length; i++) {
      const prev = curState.il[i] || 0;
      const now = result.state.il[i] || 0;
      if (now > prev) insightChanges.push({ obs: i, prevIL: prev, newIL: now });
    }

    // Apply monocle reoptimization
    result.state.md = chooseMonoTargets(
      {gl: result.state.gl, so: result.state.so, md: result.state.md, il: result.state.il, ip: result.state.ip, occ: result.state.occ, rLv: result.state.rLv, mMax},
      undefined, 72
    );
    const ctx = makeCtx(result.state.gl);
    result.state.expHr = simTotalExpWith(
      result.state.gl, result.state.so, result.state.md, result.state.il,
      result.state.occ, result.state.rLv, ctx
    );

    // Record what monocles are targeting now
    const monoTargets = [...getMonoObsSet(result.state.md)];

    // Record timeline entry
    for (const ic of insightChanges) {
      timeline.push({
        time: cumTime,
        obs: ic.obs,
        prevIL: ic.prevIL,
        newIL: ic.newIL,
        monoTargets: [...new Set(monoTargets)],
        expHr: result.state.expHr,
      });
    }

    // Create hidden intermediate node
    const interNode = _dtCreateNode(curParentId, result.event, result.time, result.state);
    interNode._autoInsightChild = true;

    // Advance
    curParentId = interNode.id;
    curState = _dtCloneState(result.state);
  }
  return null; // safety limit reached
}

// ===== TREE LAYOUT =====
function _dtIsNodeVisible(node) {
  if (node._autoInsightChild) return false; // always hidden (overrides global toggle)
  if (!DT.showLevelUpsOnly) return true;
  return node.event !== 'insight-up';
}
function _dtVisibleParent(node) {
  // Walk up to find nearest visible ancestor
  let cur = node.parentId !== null ? _dtGetNode(node.parentId) : null;
  while (cur && !_dtIsNodeVisible(cur)) cur = cur.parentId !== null ? _dtGetNode(cur.parentId) : null;
  return cur;
}
function _dtVisibleChildren(nodeId) {
  // Get all visible descendants reachable through hidden intermediate nodes
  const result = [];
  function collect(id) {
    for (const ch of _dtGetChildren(id)) {
      if (_dtIsNodeVisible(ch)) result.push(ch);
      else collect(ch.id);
    }
  }
  collect(nodeId);
  return result;
}
export function _dtToggleLevelUpsOnly() {
  DT.showLevelUpsOnly = !DT.showLevelUpsOnly;
  const btn = document.getElementById('dt-lvl-toggle');
  if (btn) {
    btn.style.background = DT.showLevelUpsOnly ? '#4a6a3a' : '#1a1a2e';
    btn.style.color = DT.showLevelUpsOnly ? '#c8e6c0' : '#ccc';
  }
  // If currently editing a hidden node, deselect
  if (DT.modalNodeId !== null) {
    const node = _dtGetNode(DT.modalNodeId);
    if (node && !_dtIsNodeVisible(node)) {
      _dtCloseModal();
      document.getElementById('dt-detail').style.display = 'none';
    }
  }
  _dtRenderTree();
}
export function _dtToggleAutoInsight() {
  if (DT.modalNodeId === null) return;
  const node = _dtGetNode(DT.modalNodeId);
  if (!node) return;
  node.autoInsight = !node.autoInsight;
  _dtUpdateAutoInsightBtn(node);
  // Update save button label to reflect new mode
  const saveBtn = document.getElementById('dt-save');
  if (saveBtn && _dtGetChildren(node.id).length === 0) {
    if (node.event === 'start') {
      saveBtn.innerHTML = '&#128190; New Branch';
    } else {
      saveBtn.innerHTML = node.autoInsight ? '&#128190; Save &amp; Auto-Ins' : '&#128190; Save &amp; Next';
    }
  }
  _dtRenderTree();
}
function _dtUpdateAutoInsightBtn(node) {
  const btn = document.getElementById('dt-auto-insight');
  if (!btn) return;
  const on = node && node.autoInsight;
  btn.style.background = on ? '#4a3a6a' : '#1a1a2e';
  btn.style.color = on ? '#d4b8f0' : '#ccc';
  btn.style.borderColor = on ? '#ce93d8' : '#555';
}
function _dtLayout() {
  if (_dtNodes.length === 0) return;
  const root = _dtGetRoot();
  if (!root) return;

  // Assign branch indices for coloring
  let branchCounter = 0;
  function assignBranch(node, brIdx) {
    node._branchIdx = brIdx;
    const children = _dtGetChildren(node.id);
    for (let i = 0; i < children.length; i++) {
      assignBranch(children[i], i === 0 ? brIdx : ++branchCounter);
    }
  }
  assignBranch(root, branchCounter++);

  // Compute total time for every node
  for (const n of _dtNodes) n._totalTime = _dtGetTotalTime(n);

  // Start's direct children (decision edits at t=0) get a small offset
  // so they don't overlap the start node visually.
  for (const n of _dtNodes) {
    if (n.parentId !== null && _dtGetNode(n.parentId)?.event === 'start' && n._totalTime === 0) {
      n._totalTime = -0.001; // tiny negative â†’ will sort right after start
    }
  }
  // Ensure start itself is the earliest
  if (root._totalTime === 0) root._totalTime = -0.002;

  // Collect all unique total-times from VISIBLE nodes and sort them to build time columns
  const visibleNodes = _dtNodes.filter(n => _dtIsNodeVisible(n));
  const timeSet = [...new Set(visibleNodes.map(n => n._totalTime))].sort((a, b) => a - b);
  const minColW = _DT_COL_W;
  const timeToX = new Map();
  let cumX = 0;
  for (let i = 0; i < timeSet.length; i++) {
    timeToX.set(timeSet[i], cumX);
    if (i < timeSet.length - 1) {
      const gap = timeSet[i + 1] - timeSet[i];
      // Synthetic gaps (start â†’ edit) get just minimum spacing
      if (gap < 0.01) {
        cumX += minColW;
      } else {
        // Square-root scale: compresses large gaps, preserves small ones
        // sqrt(gap_in_hours) * scale + minimum
        cumX += minColW + Math.sqrt(gap) * 50;
      }
    }
  }

  // Recursive layout: depth-first, only visible nodes get positions
  let nextLeafY = 0;
  function layout(node) {
    if (!_dtIsNodeVisible(node)) {
      // Skip hidden nodes, layout their children directly
      for (const ch of _dtGetChildren(node.id)) layout(ch);
      return;
    }
    node._x = _DT_PAD + (timeToX.get(node._totalTime) || 0);
    // Visible children = own visible children + visible descendants of hidden children
    const visChildren = _dtVisibleChildren(node.id);
    if (visChildren.length === 0) {
      node._y = _DT_PAD + nextLeafY * _DT_ROW_H;
      nextLeafY++;
    } else {
      for (const ch of visChildren) layout(ch);
      const ys = visChildren.map(c => c._y);
      node._y = (Math.min(...ys) + Math.max(...ys)) / 2;
    }
  }
  layout(root);
}

// Build compact change summary lines for a tree node card
function _dtNodeChangeSummary(node) {
  if (!node || node.parentId === null) return [];
  const parent = _dtGetNode(node.parentId);
  if (!parent) return [];
  const lines = [];
  const pgl = parent.baseState.gl, ngl = node.baseState.gl;

  // Grid changes - show abbreviated upgrade names
  const gridParts = [];
  for (const idx of Object.keys(RES_GRID_RAW)) {
    const i = Number(idx);
    const pv = pgl[i] || 0, nv = ngl[i] || 0;
    if (nv !== pv) {
      let name = RES_GRID_RAW[i][0].replace(/_/g, ' ');
      if (name.length > 12) name = name.slice(0, 11) + '\u2026';
      gridParts.push(name + ' +' + (nv - pv));
    }
  }
  if (gridParts.length > 0) {
    // Fit as many as we can in ~160px at 9px font
    let text = gridParts[0];
    for (let i = 1; i < gridParts.length; i++) {
      const next = text + ', ' + gridParts[i];
      if (next.length > 28) { text += ' +' + (gridParts.length - i) + ' more'; break; }
      text = next;
    }
    lines.push({ text, color: '#8cf' });
  }

  // Shape changes
  const psp = parent.baseState.sp, nsp = node.baseState.sp;
  const movedShapes = [];
  for (let i = 0; i < Math.max(psp.length, nsp.length); i++) {
    const ps = psp[i] || {}, ns = nsp[i] || {};
    if (ps.x !== ns.x || ps.y !== ns.y || ps.rot !== ns.rot) {
      movedShapes.push(SHAPE_NAMES?.[i] || ('S' + (i + 1)));
    }
  }
  if (movedShapes.length > 0) {
    let text = movedShapes.slice(0, 3).join(', ');
    if (movedShapes.length > 3) text += ' +' + (movedShapes.length - 3);
    lines.push({ text: '\u25C6 ' + text, color: '#c9a' });
  }

  // Mag changes
  const pmd = parent.baseState.md, nmd = node.baseState.md;
  let magDiffs = 0;
  const slotCheck = Math.max(pmd.length, nmd.length);
  for (let i = 0; i < slotCheck; i++) {
    const pm = pmd[i] || {}, nm = nmd[i] || {};
    if (pm.slot !== nm.slot || pm.type !== nm.type) magDiffs++;
  }
  if (magDiffs > 0) {
    lines.push({ text: '\uD83D\uDD2C ' + magDiffs + ' mag' + (magDiffs > 1 ? 's' : '') + ' changed', color: '#ad8' });
  }

  return lines;
}

// ===== CANVAS RENDERER =====
export function _dtRenderTree() {
  const wrap = document.getElementById('dt-tree-wrap');
  const canvas = document.getElementById('dt-tree-canvas');
  if (!canvas || _dtNodes.length === 0) { wrap.style.display = 'none'; return; }
  wrap.style.display = 'block';
  _dtLayout();

  const dpr = window.devicePixelRatio || 1;
  const visNodes = _dtNodes.filter(n => _dtIsNodeVisible(n));
  const maxX = Math.max(...visNodes.map(n => n._x)) + _DT_NODE_W + _DT_PAD * 2;
  const maxY = Math.max(...visNodes.map(n => n._y)) + _DT_NODE_H + _DT_PAD * 2;
  // Bake zoom into canvas so text renders at native resolution
  const z = DT.treeZoom;
  canvas.width = maxX * z * dpr;
  canvas.height = maxY * z * dpr;
  canvas.style.width = (maxX * z) + 'px';
  canvas.style.height = (maxY * z) + 'px';
  const ctx = canvas.getContext('2d');
  ctx.scale(z * dpr, z * dpr);
  ctx.clearRect(0, 0, maxX, maxY);

  // Draw connection lines (between visible nodes)
  for (const node of visNodes) {
    const vParent = _dtVisibleParent(node);
    if (!vParent) continue;
    const x1 = vParent._x + _DT_NODE_W;
    const y1 = vParent._y + _DT_NODE_H / 2;
    const x2 = node._x;
    const y2 = node._y + _DT_NODE_H / 2;
    const lineEvColors = { 'start': '#aaa', 'decision': '#ffa726', 'level-up': '#ffd700', 'insight-up': '#ce93d8', 'level+insight': '#4dd0e1' };
    ctx.strokeStyle = lineEvColors[node.event] || '#888';
    ctx.lineWidth = 2;
    ctx.beginPath();
    const cpx = (x1 + x2) / 2;
    ctx.moveTo(x1, y1);
    ctx.bezierCurveTo(cpx, y1, cpx, y2, x2, y2);
    ctx.stroke();
  }

  // Draw nodes (only visible)
  for (const node of visNodes) {
    const x = node._x, y = node._y;
    const isSelected = _dtCompareSet.has(node.id);
    const isActive = node.id === DT.modalNodeId;
    const isLeaf = _dtVisibleChildren(node.id).length === 0;
    const nodeEvColors = { 'start': '#aaa', 'decision': '#ffa726', 'level-up': '#ffd700', 'insight-up': '#ce93d8', 'level+insight': '#4dd0e1' };
    const evColor = nodeEvColors[node.event] || '#888';

    // Card background
    ctx.fillStyle = isSelected ? '#1a2a1a' : isActive ? '#1e1e3a' : '#1a1a2e';
    ctx.strokeStyle = isSelected ? '#4caf50' : isActive ? '#64b5f6' : evColor;
    ctx.lineWidth = isSelected ? 2.5 : isActive ? 2.5 : isLeaf ? 2 : 1.4;
    _dtRoundRect(ctx, x, y, _DT_NODE_W, _DT_NODE_H, 8);
    ctx.fill();
    ctx.stroke();

    // Event badge
    const evLabels = { 'start': '\u25B6 Start', 'decision': '\u270F\uFE0F Edit', 'level-up': '\u2B06 Lv Up', 'insight-up': '\uD83D\uDD2E Insight', 'level+insight': '\u2B06+\uD83D\uDD2E Both' };
    ctx.font = 'bold 10px system-ui, sans-serif';
    ctx.fillStyle = evColor;
    ctx.fillText(evLabels[node.event] || node.event, x + 8, y + 13);

    // Level + Exp/hr
    ctx.font = 'bold 12px system-ui, sans-serif';
    ctx.fillStyle = '#eee';
    ctx.fillText('Lv ' + node.rLv, x + 8, y + 28);
    ctx.font = '10px system-ui, sans-serif';
    ctx.fillStyle = '#81c784';
    ctx.fillText(fmtVal(node.expHr) + '/hr', x + 55, y + 28);

    // Exp/hr diff from visible parent
    const vPar = _dtVisibleParent(node);
    if (vPar) {
      if (vPar.expHr > 0) {
        const diff = node.expHr - vPar.expHr;
        if (diff !== 0) {
          const pct = ((diff / vPar.expHr) * 100).toFixed(1);
          const sign = diff >= 0 ? '+' : '';
          ctx.font = '9px system-ui, sans-serif';
          ctx.fillStyle = diff >= 0 ? '#81c784' : '#e57373';
          ctx.fillText(sign + fmtVal(diff) + ' (' + sign + pct + '%)', x + 8, y + 39);
        }
      }
    }

    // Time from start
    ctx.font = '10px system-ui, sans-serif';
    ctx.fillStyle = '#888';
    const totalTimeFromRoot = _dtGetTotalTime(node);
    ctx.fillText(fmtTime(totalTimeFromRoot), x + 8, y + 52);

    // Grid points indicator
    const avail = _dtGridPointsAvail(node.baseState.gl, node.rLv);
    if (avail > 0) {
      ctx.font = 'bold 10px system-ui, sans-serif';
      ctx.fillStyle = '#ffd700';
      ctx.fillText('+' + avail + 'pts', x + 80, y + 52);
    }

    // Leaf indicator
    if (isLeaf) {
      ctx.font = '10px system-ui, sans-serif';
      ctx.fillStyle = evColor;
      ctx.fillText('\u25BA', x + _DT_NODE_W - 14, y + _DT_NODE_H / 2 + 3);
    }

    // Auto-insight indicator
    if (node.autoInsight) {
      ctx.font = 'bold 9px system-ui, sans-serif';
      ctx.fillStyle = '#ce93d8';
      ctx.fillText('AI\u25B8', x + _DT_NODE_W - 22, y + 13);
    }

  }
}

function _dtRoundRect(ctx, x, y, w, h, r) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

// Get cumulative time from root to a node by walking up the parent chain
function _dtGetTotalTime(node) {
  let total = 0;
  let cur = node;
  while (cur) {
    total += cur.time;
    cur = cur.parentId !== null ? _dtGetNode(cur.parentId) : null;
  }
  return total;
}

// ===== TREE CANVAS PAN + CLICK + ZOOM =====

export function _dtTreeMouseDown(e) {
  if (e.button !== 0) return;
  // Ignore events from UI overlays inside the wrap
  if (e.target.closest('#dt-detail, #dt-comparison, #dt-top-controls, #dt-zoom-controls')) return;
  e.preventDefault(); // prevent text selection
  DT.treeDrag = { startX: e.clientX, startY: e.clientY, panX: DT.treePan.x, panY: DT.treePan.y, moved: false };
  e.currentTarget.style.cursor = 'grabbing';
  // Pointer capture keeps events flowing to the wrap even when cursor leaves it
  e.currentTarget.setPointerCapture(e.pointerId);
}
export function _dtTreeMouseMove(e) {
  if (DT.treeDrag) {
    const dx = e.clientX - DT.treeDrag.startX;
    const dy = e.clientY - DT.treeDrag.startY;
    if (Math.abs(dx) > 3 || Math.abs(dy) > 3) DT.treeDrag.moved = true;
    DT.treePan.x = DT.treeDrag.panX + dx;
    DT.treePan.y = DT.treeDrag.panY + dy;
    const canvas = document.getElementById('dt-tree-canvas');
    if (canvas) _dtApplyTreeTransform(canvas);
    _dtHideTreeTooltip();
    return;
  }
  // Hover detection for tooltip
  const canvas = document.getElementById('dt-tree-canvas');
  if (!canvas) return;
  const rect = canvas.getBoundingClientRect();
  const mx = (e.clientX - rect.left) / rect.width * (parseFloat(canvas.style.width) / DT.treeZoom);
  const my = (e.clientY - rect.top) / rect.height * (parseFloat(canvas.style.height) / DT.treeZoom);
  let found = null;
  for (const node of _dtNodes) {
    if (!_dtIsNodeVisible(node)) continue;
    if (mx >= node._x && mx <= node._x + _DT_NODE_W && my >= node._y && my <= node._y + _DT_NODE_H) {
      found = node; break;
    }
  }
  if (found !== DT.treeHoverNode) {
    DT.treeHoverNode = found;
    if (found) _dtShowTreeTooltip(found, e.clientX, e.clientY);
    else _dtHideTreeTooltip();
  } else if (found) {
    // Update position
    const tip = document.getElementById('dt-tree-tooltip');
    if (tip) { tip.style.left = (e.clientX + 12) + 'px'; tip.style.top = (e.clientY + 12) + 'px'; }
  }
}
export function _dtTreeMouseUp(e) {
  const wasDrag = DT.treeDrag && DT.treeDrag.moved;
  DT.treeDrag = null;
  const wrap = document.getElementById('dt-tree-wrap');
  if (wrap) {
    wrap.style.cursor = 'grab';
    if (wrap.hasPointerCapture(e.pointerId)) wrap.releasePointerCapture(e.pointerId);
  }
  if (wasDrag) return;
  // Ignore events from UI overlays inside the wrap
  if (e.target.closest('#dt-detail, #dt-comparison, #dt-top-controls, #dt-zoom-controls')) return;
  // Click - find node
  const canvas = document.getElementById('dt-tree-canvas');
  if (!canvas) return;
  const rect = canvas.getBoundingClientRect();
  const mx = (e.clientX - rect.left) / rect.width * (parseFloat(canvas.style.width) / DT.treeZoom);
  const my = (e.clientY - rect.top) / rect.height * (parseFloat(canvas.style.height) / DT.treeZoom);
  for (const node of _dtNodes) {
    if (!_dtIsNodeVisible(node)) continue;
    if (mx >= node._x && mx <= node._x + _DT_NODE_W && my >= node._y && my <= node._y + _DT_NODE_H) {
      _dtOpenModal(node.id);
      return;
    }
  }
  // Clicked empty space - deselect
  _dtCloseModal();
  document.getElementById('dt-detail').style.display = 'none';
  _dtRenderTree();
}
export function _dtTreeMouseLeave() {
  // Only clear hover state, not drag (drag is handled globally now)
  DT.treeHoverNode = null;
  _dtHideTreeTooltip();
  if (!DT.treeDrag) {
    const wrap = document.getElementById('dt-tree-wrap');
    if (wrap) wrap.style.cursor = 'grab';
  }
}

function _dtApplyTreeTransform(canvas) {
  if (!canvas) canvas = document.getElementById('dt-tree-canvas');
  if (!canvas) return;
  canvas.style.transformOrigin = '0 0';
  canvas.style.transform = `translate(${DT.treePan.x}px, ${DT.treePan.y}px)`;
  // Reposition editor overlay if open
  if (DT.modalNodeId !== null) {
    const node = _dtGetNode(DT.modalNodeId);
    if (node) _dtPositionEditor(node);
  }
}

export function _dtTreeWheel(e) {
  e.preventDefault();
  const delta = e.deltaY > 0 ? -0.1 : 0.1;
  const newZoom = Math.max(0.2, Math.min(2, DT.treeZoom + delta));
  // Zoom toward mouse pointer
  const wrap = document.getElementById('dt-tree-wrap');
  if (wrap) {
    const rect = wrap.getBoundingClientRect();
    const mx = e.clientX - rect.left;
    const my = e.clientY - rect.top;
    DT.treePan.x = mx - (mx - DT.treePan.x) * (newZoom / DT.treeZoom);
    DT.treePan.y = my - (my - DT.treePan.y) * (newZoom / DT.treeZoom);
  }
  DT.treeZoom = newZoom;
  _dtRenderTree();
  _dtApplyTreeTransform();
  _dtUpdateZoomLabel();
}

export function _dtTreeZoomIn() {
  DT.treeZoom = Math.min(2, DT.treeZoom + 0.15);
  _dtRenderTree();
  _dtApplyTreeTransform();
  _dtUpdateZoomLabel();
}

export function _dtTreeZoomOut() {
  DT.treeZoom = Math.max(0.2, DT.treeZoom - 0.15);
  _dtRenderTree();
  _dtApplyTreeTransform();
  _dtUpdateZoomLabel();
}

export function _dtTreeZoomReset() {
  DT.treeZoom = 1;
  DT.treePan = { x: 0, y: 0 };
  _dtRenderTree();
  _dtApplyTreeTransform();
  _dtUpdateZoomLabel();
}

function _dtUpdateZoomLabel() {
  const lbl = document.getElementById('dt-zoom-label');
  if (lbl) lbl.textContent = Math.round(DT.treeZoom * 100) + '%';
}

// ===== TREE NODE TOOLTIP =====
function _dtShowTreeTooltip(node, cx, cy) {
  let tip = document.getElementById('dt-tree-tooltip');
  if (!tip) {
    tip = document.createElement('div');
    tip.id = 'dt-tree-tooltip';
    tip.style.cssText = 'position:fixed;z-index:9999;background:#16162a;border:1px solid #555;border-radius:6px;padding:8px 10px;font-size:12px;color:#ddd;pointer-events:none;max-width:360px;line-height:1.5;white-space:pre-wrap;max-height:60vh;overflow-y:auto;';
    document.body.appendChild(tip);
  }
  const evLabels = { 'start': '\u25B6 Start', 'decision': '\u270F\uFE0F Edit', 'level-up': '\u2B06 Level Up', 'insight-up': '\uD83D\uDD2E Insight Up', 'level+insight': '\u2B06+\uD83D\uDD2E Both' };
  const evColors = { 'start': '#aaa', 'decision': '#ffa726', 'level-up': '#ffd700', 'insight-up': '#ce93d8', 'level+insight': '#4dd0e1' };
  const totalTime = _dtGetTotalTime(node);
  const avail = _dtGridPointsAvail(node.baseState.gl, node.rLv);

  let html = `<div style="color:${evColors[node.event] || '#aaa'};font-weight:700;margin-bottom:4px;">${evLabels[node.event] || node.event}</div>`;
  html += `<div><span style="color:#aaa;">Level:</span> <b style="color:#eee;">${node.rLv}</b></div>`;
  html += `<div><span style="color:#aaa;">EXP/hr:</span> <b style="color:#81c784;">${fmtVal(node.expHr)}</b>`;
  if (node.parentId !== null) {
    const parent = _dtGetNode(node.parentId);
    if (parent && parent.expHr > 0) {
      const diff = node.expHr - parent.expHr;
      if (diff !== 0) {
        const pct = ((diff / parent.expHr) * 100).toFixed(1);
        const sign = diff >= 0 ? '+' : '';
        const color = diff >= 0 ? '#81c784' : '#e57373';
        html += ` <span style="color:${color};font-size:11px;">(${sign}${fmtVal(diff)}, ${sign}${pct}%)</span>`;
      }
    }
  }
  html += `</div>`;
  html += `<div><span style="color:#aaa;">Time:</span> <b>${fmtTime(totalTime)}</b></div>`;
  if (avail > 0) html += `<div><span style="color:#aaa;">Grid pts:</span> <b style="color:#ffd700;">+${avail}</b></div>`;

  // Changes from parent
  const changes = _dtNodeChangeSummary(node);
  if (changes.length > 0) {
    html += `<div style="margin-top:5px;padding-top:5px;border-top:1px solid #333;font-size:11px;">`;
    html += `<div style="color:#aaa;margin-bottom:2px;">Changes from parent:</div>`;
    for (const ch of changes) {
      html += `<div style="color:${ch.color || '#aaa'};">${ch.text}</div>`;
    }
    html += `</div>`;
  }

  // Insight timeline (from auto-insight chain)
  if (node.insightTimeline && node.insightTimeline.length > 0) {
    html += `<div style="margin-top:5px;padding-top:5px;border-top:1px solid #555;font-size:11px;">`;
    html += `<div style="color:#ce93d8;font-weight:600;margin-bottom:3px;">Auto-Insight Timeline (${node.insightTimeline.length})</div>`;
    for (const entry of node.insightTimeline) {
      const obsName = (OCC_DATA[entry.obs] ? OCC_DATA[entry.obs].name.replace(/_/g, ' ') : 'Obs ' + entry.obs);
      const monoStr = entry.monoTargets.map(t => OCC_DATA[t] ? OCC_DATA[t].name.replace(/_/g, ' ') : 'Obs ' + t).join(', ');
      html += `<div style="color:#ddd;"><span style="color:#888;">${fmtTime(entry.time)}</span> ${obsName} Lv ${entry.prevIL} &rarr; ${entry.newIL}</div>`;
      html += `<div style="color:#ad8;margin-left:12px;font-size:10px;">Mono &rarr; ${monoStr} <span style="color:#81c784;">${fmtVal(entry.expHr)}/hr</span></div>`;
    }
    html += `</div>`;
  }

  tip.innerHTML = html;
  tip.style.left = (cx + 12) + 'px';
  tip.style.top = (cy + 12) + 'px';
  tip.style.display = 'block';
}

function _dtHideTreeTooltip() {
  const tip = document.getElementById('dt-tree-tooltip');
  if (tip) tip.style.display = 'none';
}

// Info icon tooltip
let _dtInfoTip = null;
export function _dtShowInfoTip(e) {
  if (!_dtInfoTip) {
    _dtInfoTip = document.createElement('div');
    _dtInfoTip.style.cssText = 'position:fixed;z-index:9999;background:#16162a;border:1px solid #555;border-radius:6px;padding:8px 10px;font-size:12px;color:#ddd;pointer-events:none;max-width:280px;line-height:1.5;white-space:pre-wrap;';
    document.body.appendChild(_dtInfoTip);
  }
  _dtInfoTip.innerHTML = `<div style="color:var(--purple);font-weight:700;margin-bottom:4px;">Interactive Decision Tree</div>`
    + `<div style="color:#bbb;">Step through research events one at a time. Make choices at each node, then advance to the next event.</div>`
    + `<div style="color:#bbb;margin-top:4px;">Branch from any node to explore alternative paths and compare outcomes.</div>`;
  _dtInfoTip.style.left = (e.clientX + 12) + 'px';
  _dtInfoTip.style.top = (e.clientY + 12) + 'px';
  _dtInfoTip.style.display = 'block';
}
export function _dtMoveInfoTip(e) {
  if (_dtInfoTip) { _dtInfoTip.style.left = (e.clientX + 12) + 'px'; _dtInfoTip.style.top = (e.clientY + 12) + 'px'; }
}
export function _dtHideInfoTip() {
  if (_dtInfoTip) _dtInfoTip.style.display = 'none';
}

// ===== INLINE DETAIL PANEL =====
function _dtOpenModal(nodeId) {
  const node = _dtGetNode(nodeId);
  if (!node) return;
  DT.modalNodeId = nodeId;
  DT.editState = _dtCloneState({...node.baseState, rLv: node.rLv, rExp: node.rExp, expHr: node.expHr});
  _dtRenderModal();
  _dtRenderTree();
  const detail = document.getElementById('dt-detail');
  detail.style.display = 'block';
  _dtPositionEditor(node);
}

function _dtPositionEditor(node) {
  const wrap = document.getElementById('dt-tree-wrap');
  const detail = document.getElementById('dt-detail');
  if (!wrap || !detail || !node) return;
  const wrapRect = wrap.getBoundingClientRect();
  // Node position in screen coords (account for pan + zoom)
  const nodeScreenX = node._x * DT.treeZoom + DT.treePan.x;
  const nodeScreenY = node._y * DT.treeZoom + DT.treePan.y;
  const nodeScreenW = _DT_NODE_W * DT.treeZoom;
  const nodeScreenH = _DT_NODE_H * DT.treeZoom;
  const detailW = detail.offsetWidth;
  const detailH = detail.offsetHeight;
  const gap = 12;
  // Prefer below the node; if not enough room, put above
  let top, left;
  const spaceBelow = wrapRect.height - (nodeScreenY + nodeScreenH + gap);
  const spaceAbove = nodeScreenY - gap;
  if (spaceBelow >= detailH || spaceBelow >= spaceAbove) {
    top = nodeScreenY + nodeScreenH + gap;
  } else {
    top = nodeScreenY - detailH - gap;
  }
  // Center horizontally on the node, clamp to wrap bounds
  left = nodeScreenX + nodeScreenW / 2 - detailW / 2;
  left = Math.max(8, Math.min(left, wrapRect.width - detailW - 8));
  top = Math.max(8, Math.min(top, wrapRect.height - detailH - 8));
  detail.style.left = left + 'px';
  detail.style.top = top + 'px';
}

function _dtCloseModal() {
  const popup = document.getElementById('dt-shape-rotate-popup');
  if (popup) popup.style.display = 'none';
  DT.modalNodeId = null;
  DT.editState = null;
  _dtResetGridState();
}


export function _dtRenderModal() {
  if (!DT.editState || DT.modalNodeId === null) return;
  const node = _dtGetNode(DT.modalNodeId);
  const s = DT.editState;
  const evLabels = { 'start': '\u25B6 Start', 'decision': '\u270F\uFE0F Edit', 'level-up': '\u2B06 Lv Up', 'insight-up': '\uD83D\uDD2E Insight', 'level+insight': '\u2B06+\uD83D\uDD2E Both' };

  // Title + inline status
  document.getElementById('dt-detail-title').textContent = (evLabels[node.event] || node.event) + ' - Lv ' + s.rLv;
  const totalTime = _dtGetTotalTime(node);
  const avail = _dtGridPointsAvail(s.gl, s.rLv);
  document.getElementById('dt-detail-status').innerHTML =
    `<b style="color:var(--green);">${fmtVal(s.expHr)}/hr</b> Â· ` +
    `${fmtTime(totalTime)} Â· ` +
    `<span style="color:${avail > 0 ? 'var(--gold)' : 'var(--text2)'};">${avail} pts</span> Â· ` +
    `${computeOccurrencesToBeFound(s.rLv, s.occ)} obs Â· ` +
    `${computeMagnifiersOwnedWith(s.gl, s.rLv, s.ctx || makeCtx(s.gl))} mags`;

  // Grid pts label
  document.getElementById('dt-grid-pts').textContent = `(${avail} pts)`;

  // Unified grid + shape canvas
  _dtRenderGridCanvas();

  // Obs editor
  _dtRenderObsEditor();

  // Show/hide buttons based on node type
  const delBtn = document.getElementById('dt-delete');
  const branchBtn = document.getElementById('dt-branch');
  const saveBtn = document.getElementById('dt-save');
  const autoInsBtn = document.getElementById('dt-auto-insight');
  if (delBtn) delBtn.style.display = node.parentId === null ? 'none' : '';
  if (branchBtn) branchBtn.style.display = node.event === 'start' ? 'none' : '';
  // Show auto-insight toggle only for leaves (nodes that will advance) or nodes with auto-insight chains
  const isLeaf = _dtGetChildren(node.id).length === 0;
  const hasAutoChain = _dtGetChildren(node.id).some(c => c._autoInsightChild);
  if (autoInsBtn) autoInsBtn.style.display = (isLeaf || node.event === 'start' || hasAutoChain) ? '' : 'none';
  _dtUpdateAutoInsightBtn(node);
  if (saveBtn) {
    if (node.event === 'start') {
      saveBtn.innerHTML = '&#128190; New Branch';
    } else if (!isLeaf) {
      saveBtn.innerHTML = '&#128190; Save &amp; Resim';
    } else {
      saveBtn.innerHTML = node.autoInsight ? '&#128190; Save &amp; Auto-Ins' : '&#128190; Save &amp; Next';
    }
  }
}


// ===== SAVE CHANGES (update in-place, then advance or resim) =====
export function _dtSaveChanges() {
  if (!DT.editState || DT.modalNodeId === null) return;
  const node = _dtGetNode(DT.modalNodeId);
  if (!node) return;
  const s = DT.editState;

  // Start node: never edited in-place - always fork a new branch
  if (node.event === 'start') {
    const editState = _dtCloneState(s);
    // Decision child captures user's edits at t=0
    const decNode = _dtCreateNode(node.id, 'decision', 0, editState);
    decNode.autoInsight = node.autoInsight; // propagate toggle to decision node
    // Sim forward from that decision
    if (decNode.autoInsight) {
      const finalNode = _dtAdvanceAutoInsight(decNode);
      if (!finalNode) {
        alert('Could not advance (sim did not find a research level-up within limit).');
        _dtRenderTree();
        return;
      }
      _dtRenderTree();
      _dtOpenModal(finalNode.id);
      return;
    }
    const simState = _dtCloneState(editState);
    const result = _dtStepSim(simState);
    if (!result) {
      alert('Could not advance (sim did not find an event within limit).');
      _dtRenderTree();
      return;
    }
    const eventNode = _dtCreateNode(decNode.id, result.event, result.time, result.state);
    _dtRenderTree();
    _dtOpenModal(eventNode.id);
    return;
  }

  // Update current node's state in-place
  node.baseState = _dtCloneState(s);
  node.rLv = s.rLv;
  node.rExp = s.rExp;
  node.expHr = s.expHr;

  const children = _dtGetChildren(node.id);
  if (children.length === 0) {
    // No children yet â†’ auto-advance: sim to next event, create child, open it
    if (node.autoInsight) {
      // Auto-insight: loop through insight-ups, create hidden nodes, stop at research level-up
      const finalNode = _dtAdvanceAutoInsight(node);
      if (!finalNode) {
        alert('Could not advance (sim did not find a research level-up within limit).');
        _dtRenderTree();
        return;
      }
      _dtRenderTree();
      _dtOpenModal(finalNode.id);
    } else {
      const simState = _dtCloneState({...node.baseState, rLv: node.rLv, rExp: node.rExp, expHr: node.expHr});
      const result = _dtStepSim(simState);
      if (!result) {
        alert('Could not advance (sim did not find an event within limit).');
        _dtRenderTree();
        return;
      }
      const newNode = _dtCreateNode(node.id, result.event, result.time, result.state);
      _dtRenderTree();
      _dtOpenModal(newNode.id);
    }
  } else {
    // Has children â†’ re-sim all descendants
    _dtResimChildrenOf(node);
    _dtRebuildInsightTimelines();
    _dtRenderTree();
    _dtRenderModal();
  }
}

// Compute changes between a node and its parent
function _dtComputeChanges(node) {
  if (!node || node.parentId === null) return [];
  const parent = _dtGetNode(node.parentId);
  if (!parent) return [];
  const changes = [];
  const pgl = parent.baseState.gl, ngl = node.baseState.gl;
  // Grid changes
  const gridChanges = [];
  for (const idx of Object.keys(RES_GRID_RAW)) {
    const i = Number(idx);
    const pv = pgl[i] || 0, nv = ngl[i] || 0;
    if (nv !== pv) {
      const name = RES_GRID_RAW[i][0].replace(/_/g, ' ');
      gridChanges.push(`${name} ${pv}\u2192${nv}`);
    }
  }
  if (gridChanges.length > 0) changes.push('Grid: ' + gridChanges.join(', '));
  // Mag changes: count by slot+type
  const magKey = (md) => {
    const m = {};
    for (const mag of md) { const k = mag.slot + ':' + mag.type; m[k] = (m[k]||0)+1; }
    return m;
  };
  const pmk = magKey(parent.baseState.md), nmk = magKey(node.baseState.md);
  const allMagKeys = new Set([...Object.keys(pmk), ...Object.keys(nmk)]);
  let magDiffs = 0;
  for (const k of allMagKeys) { if ((pmk[k]||0) !== (nmk[k]||0)) magDiffs++; }
  if (magDiffs > 0) changes.push(`Mags: ${magDiffs} change${magDiffs>1?'s':''}`);
  // Shape changes
  const psp = parent.baseState.sp, nsp = node.baseState.sp;
  let shapeDiffs = 0;
  for (let i = 0; i < Math.max(psp.length, nsp.length); i++) {
    const ps = psp[i] || {}, ns = nsp[i] || {};
    if (ps.x !== ns.x || ps.y !== ns.y || ps.rot !== ns.rot) shapeDiffs++;
  }
  if (shapeDiffs > 0) changes.push(`Shapes: ${shapeDiffs} moved`);
  return changes;
}

// ===== COMPARISON =====
function _dtToggleCompare(nodeId) {
  if (_dtCompareSet.has(nodeId)) _dtCompareSet.delete(nodeId);
  else _dtCompareSet.add(nodeId);
  _dtRenderTree();
  _dtRenderComparison();
}

export function _dtRenderComparison() {
  const panel = document.getElementById('dt-comparison');
  const body = document.getElementById('dt-comparison-body');
  if (_dtCompareSet.size < 1) { panel.style.display = 'none'; return; }
  panel.style.display = 'block';

  const nodes = [..._dtCompareSet].map(id => _dtGetNode(id)).filter(Boolean);
  let html = '<div style="display:grid;grid-template-columns:repeat(' + Math.min(nodes.length, 4) + ',1fr);gap:10px;">';
  for (const n of nodes) {
    const totalTime = _dtGetTotalTime(n);
    const brColor = _DT_BRANCH_COLORS[n._branchIdx % _DT_BRANCH_COLORS.length];
    const avail = _dtGridPointsAvail(n.baseState.gl, n.rLv);
    const changes = _dtComputeChanges(n);
    html += `<div style="background:#1a1a2e;border:2px solid ${brColor};border-radius:8px;padding:12px;">`;
    html += `<div style="color:${brColor};font-weight:700;margin-bottom:6px;">Node #${n.id} <span style="color:var(--text2);font-weight:400;font-size:.8em;">${n.event}</span></div>`;
    html += `<div style="font-size:.85em;">`;
    html += `<div style="display:flex;justify-content:space-between;"><span style="color:var(--text2);">Level</span><b style="color:var(--gold);">${n.rLv}</b></div>`;
    html += `<div style="display:flex;justify-content:space-between;"><span style="color:var(--text2);">EXP/hr</span><b style="color:var(--green);">${fmtVal(n.expHr)}</b></div>`;
    html += `<div style="display:flex;justify-content:space-between;"><span style="color:var(--text2);">Time</span><b>${fmtTime(totalTime)}</b></div>`;
    html += `<div style="display:flex;justify-content:space-between;"><span style="color:var(--text2);">Grid pts avail</span><b style="color:var(--gold);">${avail}</b></div>`;
    if (changes.length > 0) {
      html += `<div style="margin-top:6px;padding-top:6px;border-top:1px solid #333;">`;
      for (const c of changes) html += `<div style="color:#ffa726;font-size:.82em;">\u270F ${c}</div>`;
      html += `</div>`;
    }
    html += `</div>`;
    html += `<div style="display:flex;gap:4px;margin-top:8px;">`;
    html += `<button class="btn btn-sm" style="background:#335;flex:1;" data-dt-open="${n.id}">Open</button>`;
    html += `<button class="btn btn-sm" style="background:#f44336;flex:1;" data-dt-delete="${n.id}">Delete</button>`;
    html += `<button class="btn btn-sm" style="background:#444;flex:1;" data-dt-remove="${n.id}">Remove</button>`;
    html += `</div>`;
    html += `</div>`;
  }
  html += '</div>';
  body.innerHTML = html;

  // Event delegation for comparison panel buttons
  body.addEventListener('click', (e) => {
    const openBtn = e.target.closest('[data-dt-open]');
    if (openBtn) { _dtOpenModal(Number(openBtn.dataset.dtOpen)); return; }
    const delBtn = e.target.closest('[data-dt-delete]');
    if (delBtn) { _dtDeleteNode(Number(delBtn.dataset.dtDelete)); _dtRenderComparison(); return; }
    const remBtn = e.target.closest('[data-dt-remove]');
    if (remBtn) { _dtToggleCompare(Number(remBtn.dataset.dtRemove)); return; }
  });
}

// ===== DELETE NODE + DESCENDANTS =====
export function _dtDeleteNode(nodeId) {
  const targetId = nodeId != null ? nodeId : DT.modalNodeId;
  if (targetId === null) return;
  const node = _dtGetNode(targetId);
  if (!node || node.parentId === null) return; // can't delete root

  // Collect all descendant IDs
  const toDelete = new Set();
  function collect(id) {
    toDelete.add(id);
    const n = _dtGetNode(id);
    if (n) for (const cid of n.childIds) collect(cid);
  }
  collect(node.id);

  // Remove from parent's childIds
  const parent = _dtGetNode(node.parentId);
  if (parent) parent.childIds = parent.childIds.filter(cid => !toDelete.has(cid));

  // Remove from compare set
  for (const id of toDelete) _dtCompareSet.delete(id);

  // Remove from nodes array
  for (let i = _dtNodes.length - 1; i >= 0; i--) {
    if (toDelete.has(_dtNodes[i].id)) _dtNodes.splice(i, 1);
  }

  // If the deleted node was being edited, open parent instead
  if (DT.modalNodeId !== null && toDelete.has(DT.modalNodeId)) {
    _dtCloseModal();
    if (parent) _dtOpenModal(parent.id);
  }
  _dtRenderTree();
  _dtRenderComparison();
}

// ===== RE-SIM DOWNSTREAM (helper) =====
function _dtResimChildrenOf(parentNode) {
  // Copy childIds since auto-insight rebuild may modify the array
  const origChildIds = parentNode.childIds.slice();
  for (const childId of origChildIds) {
    const child = _dtGetNode(childId);
    if (!child) continue;

    if (child._autoInsightChild) {
      // Auto-insight chain detected - tear down and rebuild so node count/events stay correct
      // 1. Walk the chain to collect all hidden nodes + the final visible node
      const chainIds = [];
      let cur = child;
      while (cur && cur._autoInsightChild) {
        chainIds.push(cur.id);
        const kids = _dtGetChildren(cur.id);
        cur = kids.length > 0 ? kids[0] : null;
      }
      // cur = final visible node at end of chain (or null if chain ends abruptly)
      let savedChildIds = [];
      if (cur) {
        chainIds.push(cur.id);
        savedChildIds = cur.childIds.slice();
      }
      // 2. Clean up compare set for deleted nodes
      const chainSet = new Set(chainIds);
      for (const cid of chainIds) _dtCompareSet.delete(cid);
      // 3. Remove chain start from parent's childIds
      parentNode.childIds = parentNode.childIds.filter(id => id !== childId);
      // 4. Remove all chain nodes from _dtNodes
      for (let i = _dtNodes.length - 1; i >= 0; i--) {
        if (chainSet.has(_dtNodes[i].id)) _dtNodes.splice(i, 1);
      }
      // 5. Rebuild chain if auto-insight still enabled, otherwise single normal step
      let newTail = null;
      if (parentNode.autoInsight) {
        newTail = _dtAdvanceAutoInsight(parentNode);
      } else {
        // Auto-insight was turned off - replace chain with a single sim step
        const ps = _dtCloneState({...parentNode.baseState, rLv: parentNode.rLv, rExp: parentNode.rExp, expHr: parentNode.expHr});
        const r = _dtStepSim(ps);
        if (r) newTail = _dtCreateNode(parentNode.id, r.event, r.time, r.state);
      }
      // 6. Re-attach saved children to the new tail node and continue resimming
      if (newTail && savedChildIds.length > 0) {
        for (const scId of savedChildIds) {
          const sc = _dtGetNode(scId);
          if (sc) sc.parentId = newTail.id;
        }
        newTail.childIds.push(...savedChildIds);
        _dtResimChildrenOf(newTail);
      } else if (!newTail && savedChildIds.length > 0) {
        // Fallback: re-attach to parent and resim normally
        for (const scId of savedChildIds) {
          const sc = _dtGetNode(scId);
          if (sc) sc.parentId = parentNode.id;
        }
        parentNode.childIds.push(...savedChildIds);
        for (const scId of savedChildIds) {
          const sc = _dtGetNode(scId);
          if (sc) _dtResimChildrenOf(sc);
        }
      }
      continue;
    }

    // Normal resim for non-auto-insight children
    const parentState = _dtCloneState({...parentNode.baseState, rLv: parentNode.rLv, rExp: parentNode.rExp, expHr: parentNode.expHr});
    const result = _dtStepSim(parentState);
    if (result) {
      child.event = result.event;
      child.time = result.time;
      child.rLv = result.state.rLv;
      child.rExp = result.state.rExp;
      child.expHr = result.state.expHr;
      child.baseState = _dtCloneState(result.state);
    }
    _dtResimChildrenOf(child);
  }
}

// Rebuild insightTimeline on a node by walking back through its auto-insight ancestors
function _dtRebuildInsightTimelines() {
  for (const node of _dtNodes) {
    if (node._autoInsightChild || !node.insightTimeline) continue;
    // Walk backwards to collect the auto-insight chain
    const chain = [];
    let cur = node;
    while (cur.parentId !== null) {
      const p = _dtGetNode(cur.parentId);
      if (p && p._autoInsightChild) { chain.unshift(p); cur = p; }
      else break;
    }
    if (chain.length === 0) { node.insightTimeline = null; continue; }
    // cur is now the first auto-insight child; its parent is the chain origin
    const originParent = cur.parentId !== null ? _dtGetNode(cur.parentId) : null;
    let prevILArr = originParent ? originParent.baseState.il : [];
    const timeline = [];
    let cumT = 0;
    for (const cn of chain) {
      cumT += cn.time;
      for (let i = 0; i < cn.baseState.il.length; i++) {
        const prev = prevILArr[i] || 0;
        const now = cn.baseState.il[i] || 0;
        if (now > prev) {
          const monoTargets = [...getMonoObsSet(cn.baseState.md)];
          timeline.push({ time: cumT, obs: i, prevIL: prev, newIL: now, monoTargets, expHr: cn.expHr });
        }
      }
      prevILArr = cn.baseState.il;
    }
    node.insightTimeline = timeline.length > 0 ? timeline : null;
  }
}

// ===== RESET =====
export function _dtReset() {
  _dtNodes.length = 0;
  DT.nextId = 1;
  _dtCompareSet.clear();
  _dtCloseModal();
  document.getElementById('dt-detail').style.display = 'none';
  document.getElementById('dt-tree-wrap').style.display = 'none';
  document.getElementById('dt-comparison').style.display = 'none';
  DT.treePan = { x: 0, y: 0 };
  DT.treeZoom = 1;
  const tc = document.getElementById('dt-tree-canvas');
  if (tc) _dtApplyTreeTransform(tc);
  _dtUpdateZoomLabel();
}

// ===== BRANCH =====
// Creates a sibling copy of the current node (same event, same time),
// applies the current edit state, sims forward to the next event,
// then reverts the original node and opens the sim result.
export function _dtBranch() {
  if (!DT.editState || DT.modalNodeId === null) return;
  const node = _dtGetNode(DT.modalNodeId);
  if (!node || node.parentId === null) return; // can't branch from root
  const parent = _dtGetNode(node.parentId);
  if (!parent) return;
  const s = DT.editState;

  // Create a sibling copy of the current node with the edit state applied
  const forkState = _dtCloneState(s);
  const newNode = _dtCreateNode(parent.id, node.event, node.time, forkState);
  newNode.autoInsight = node.autoInsight;

  // Sim forward from the sibling to find next event
  if (newNode.autoInsight) {
    const finalNode = _dtAdvanceAutoInsight(newNode);
    if (!finalNode) {
      alert('Could not advance (sim did not find a research level-up within limit).');
      _dtOpenModal(node.id);
      _dtRenderTree();
      _dtOpenModal(newNode.id);
      return;
    }
    _dtOpenModal(node.id);
    _dtRenderTree();
    _dtOpenModal(finalNode.id);
    return;
  }
  const simState = _dtCloneState(forkState);
  const result = _dtStepSim(simState);
  if (!result) {
    alert('Could not advance (sim did not find an event within limit).');
    _dtOpenModal(node.id);
    _dtRenderTree();
    _dtOpenModal(newNode.id);
    return;
  }
  const eventNode = _dtCreateNode(newNode.id, result.event, result.time, result.state);

  // Revert current node, render, then open the sim result
  _dtOpenModal(node.id);
  _dtRenderTree();
  _dtOpenModal(eventNode.id);
}

// ===== START =====
export function _dtStart() {
  _dtReset();
  const initState = _dtBuildInitState();
  const root = _dtCreateNode(null, 'start', 0, initState);
  _dtRenderTree();
  _dtOpenModal(root.id);
}

// Auto-optimize mags for current edit state
export async function _dtAutoOptMags() {
  if (!DT.editState) return;
  const s = DT.editState;
  const ctx = makeCtx(s.gl);
  const mOwned = computeMagnifiersOwnedWith(s.gl, s.rLv, ctx);
  const mMax = magMaxForLevel(s.rLv);
  const optimized = await optimizeMagsFor({gl: s.gl, so: s.so, md: s.md, il: s.il, occ: s.occ, rLv: s.rLv, mOwned, mMax});
  s.md = optimized;
  s.md = chooseMonoTargets({gl: s.gl, so: s.so, md: s.md, il: s.il, ip: s.ip, occ: s.occ, rLv: s.rLv, mMax}, ctx, 72);
  _dtRecalcExpHr();
  _dtRenderModal();
}

// Auto-optimize shapes for current edit state
export function _dtAutoOptShapes() {
  if (!DT.editState) return;
  const s = DT.editState;
  const result = optimizeShapesFor({gl: s.gl, so: s.so, md: s.md, il: s.il, occ: s.occ, rLv: s.rLv});
  s.so = result.overlay;
  s.sp = result.positions;
  // Ensure unplaced shapes still have a position on the board (stacked at top-left)
  const numOwned = Math.min(computeShapesOwnedAt(s.rLv, ctx), SHAPE_VERTICES.length, 10);
  for (let si = 0; si < numOwned; si++) {
    if (!s.sp[si] || s.sp[si].x == null) {
      s.sp[si] = { x: 0, y: si * 5, rot: 0 };
    }
  }
  _dtRecalcExpHr();
  _dtRenderModal();
}


// Insight ROI + Obs Unlock renderers extracted to render-analysis.js
export { renderInsightROI, renderObsUnlock } from './render-analysis.js';


// Upgrade Eval + Shape Presets extracted to render-upgrades.js
export { _saveShapeTiers, _formatDesc, renderUpgradeEval } from './render-upgrades.js';

// ===== MAIN RENDER =====
export function renderAll() {
  renderDashboard();
  // Re-render the currently active tab
  const activeTab = document.querySelector('.tab.active');
  if (activeTab) {
    const t = activeTab.dataset.tab;
    if (t === 'insight-roi') renderInsightROI();
    else if (t === 'obs-unlock') renderObsUnlock();
    else if (t === 'shape-opt') renderUpgradeEval();
  }
  // Set default target level for optimizer (always current + 1)
  const targetInput = document.getElementById('opt-target-level');
  if (targetInput) {
    targetInput.value = researchLevel + 1;
  }
  const sbTarget = document.getElementById('sb-target-value');
  if (sbTarget) {
    sbTarget.value = researchLevel + 1;
  }
}
