// ===== SUSHI STATION - STATIC GAME DATA =====
// Extracted from N.formatted.js CustomLists (SushiUPG, Research[32-37])

// SushiUPG[i] = [name, maxLv, costBase, bonusPerLv, costDN_override, description]
export const SUSHI_UPG = [
  ['Sushi Slot',50,3.50,1,0,'Adds a new slot for your Sushi Station!'],
  ['Fuel Capacity I',9999,1.08,50,0,'+{ max Fuel Capacity!'],
  ['Fuel Capacity II',9999,1.10,200,0,'+{ max Fuel Capacity, and a unique multiplier Fuel Cap bonus!'],
  ['Fuel Capacity III',9999,1.12,1500,0,'+{ max Fuel Capacity, and a unique multiplier Fuel Cap bonus!'],
  ['Fuel Capacity IV',9999,1.13,10000,0,'+{ max Fuel Capacity, and a unique multiplier Fuel Cap bonus!'],
  ['Fuel Capacity V',9999,1.15,50000,0,'+{ max Fuel Capacity, and a unique multiplier Fuel Cap bonus!'],
  ['Superior Sushi Skillz',35,3.80,1,.20,'You can now click the Sushi on your fuel bar to change which sushi you cook, up to Tier $. Also increases fuel cost.'],
  ['Quality Freshness',25,6.50,1,0,'{% chance for freshly cooked Sushi to be +1 higher Tier!'],
  ['Fastburn Fuel I',9999,1.10,15,0,'+{% faster Fuel generation!'],
  ['Fastburn Fuel II',9999,1.12,100,0,'+{% faster Fuel generation, and a unique Fuel Gen multi bonus!'],
  ['Fastburn Fuel III',9999,1.14,750,0,'+{% faster Fuel generation, and a unique Fuel Gen multi bonus!'],
  ['Fastburn Fuel IV',9999,1.16,5000,0,'+{% faster Fuel generation, and a unique Fuel Gen multi bonus!'],
  ['Fastburn Fuel V',9999,1.17,25000,0,'+{% faster Fuel generation, and a unique Fuel Gen multi bonus!'],
  ['Seared Knowledge',1,1.10,1,1.5,'Whenever a sushi is created, that type gains +1 EXP. Level up for knowledge bonuses!'],
  ['Hot Slot',20,20.0,1,0,'Adds a Hot Plate slot! Sushi on these generate $x more Bucks!'],
  ['Cold Slot',8,150,1,0,'Adds a Cold Plate slot! Sushi on these generate +$ EXP/day for ALL lower-tiered sushi!'],
  ['Milktoast Slot',12,70.0,1,0,'Adds a Milktoast Plate slot! Sushi on these generate +$ EXP/day.'],
  ['Salt Shaker',1,1.10,1,2,'Once/day: all sushi have a chance of getting a Tier Up!'],
  ['Pepper Shaker',1,1.10,1,3,'Once/day: all sushi have a chance to be Perfecto\'d (Knowledge Bonus 2x)!'],
  ['Saffron Shaker',1,1.10,1,4,'Once/day: all sushi generate 1 hour\'s worth of Bucks!'],
  ['Shake N\' Bake',10,100.0,1,0,'Using any Shaker generates 1 hour of Fuel! {% chance for 10 hours!'],
  ['Bottomless Shakers',20,12.0,1,0,'Using any Shaker: {% chance to get another free usage!'],
  ['Sasaphrax Saffron',23,11.0,1,0,'Saffron Shaker now generates $ hours of Bucks, not just 1!'],
  ['Charcoal Fireplace',15,40.0,1,0,'Red fireplace: +1% Fuel gen per Tier of Sushi in the column above it.'],
  ['Copper Firelighter',1,1.10,1,3,'Blue fire: {% chance of +2 tiers instead of +1 (not highest tier).'],
  ['Potassium Firelighter',1,1.10,1,5,'Purple fire: each gives +1 currency/sec.'],
  ['Lithium Firelighter',1,1.10,1,4,'Pink fire: sushi above generate $x more Knowledge EXP!'],
  ['Barium Firelighter',1,1.10,1,2,'Green fire: sushi above generate $x more Bucks.'],
  ['Overtuned Fuel',1,1.10,1,0,'When you generate fuel at max capacity, you get +1 overtuned currency.'],
  ['Heat of the East Wind',1,1.10,1,0,'When a sushi combines, it tiers-up the sushi to its right (if lower tiered). Tier $ and below.'],
  ['Customer Surcharge I',9999,1.14,2,0,'Boosts all Bucks generated by +{%'],
  ['Customer Surcharge II',9999,1.16,3,0,'All sushi generate +{% more Bucks! Unique sushi give 1.10x mult Bucks bonus.'],
  ['Customer Surcharge III',9999,1.17,5,0,'All sushi generate +{% more Bucks!'],
  ['Customer Surcharge IV',9999,1.19,10,0,'All sushi generate +{% more Bucks!'],
  ['Customer Surcharge V',9999,1.20,20,0,'All sushi generate +{% more Bucks!'],
  ['Quickpay Fee',120,2.00,1,0,'When sushi is created, instantly generates { minutes of Bucks!'],
  ['Wholesale Pricing',9999,1.15,1,0,'All upgrades are $% cheaper, now and forever!'],
  ['2nd Degree Searing',9999,1.35,1,0,'Newly created Sushi generate +$ EXP (multiplied by knowledge multi\'s).'],
  ['3rd Degree Searing',9999,1.15,1,0,'Boosts all Sushi EXP by +{% from all sources.'],
  ['Rift Guy\'s Upgrade',0,1.10,1,0,'Special Rift Guy upgrade.'],
  ['No Tax on Tips',9999,1.20,2,0,'Multiplies all Bucks earned by }x'],
  ['Hourly Wage Meter',9999,1.08,1,0,'Adds Hourly Bucks display. Also +{% total Bucks generated!'],
  ['Movement Mittens',1,1.10,1,.3,'Adds the MOVE button to drag SLOTS around.'],
  ['Sushi Tier Vision',9999,1.20,2,0,'Toggle to show Sushi Tiers numerically. Also +{% total Bucks!'],
  ['Sushi Service Bonuses',1,1.10,1,0,'Creating a new sushi type gives a new IdleOn bonus! (RoG unlocks)'],
];

// Research[32]: upgrade slot index → SushiUPG entry index
// Slot 0 unlocks first (tier 1), slot 44 unlocks last (tier 75).
export const SLOT_TO_UPG = [41,8,44,1,30,9,0,6,2,43,17,31,14,42,13,23,35,10,3,20,32,7,18,16,27,29,11,36,21,4,37,24,19,15,12,22,33,28,26,5,25,40,38,34,39];

// Research[33]: sushi tier → knowledge category (0-10)
export const TIER_TO_KNOWLEDGE_CAT = [0,1,2,0,2,3,1,0,2,4,3,0,1,5,2,4,3,0,6,3,2,5,1,4,0,6,2,7,3,5,1,6,0,4,8,2,7,5,6,3,1,8,4,9,2,7,5,8,3,10,6,9,8,10];

// Research[34]: knowledge category descriptions
export const KNOWLEDGE_CAT_DESC = [
  '+{% more Bucks generated',
  '+{% bonus Knowledge XP',
  '+^% chance for +1 Tier for cooked sushi',
  '}x higher Fuel Capacity',
  '+{% faster Fuel generation',
  '+^% chance for free shaker usage',
  '+{% cheaper upgrades',
  '}x faster Fuel generation',
  '+^% bigger effects from Slots',
  '+^% bigger effects from Fireplaces',
  '}x higher chance to Perfecto all sushi',
];

// Research[35]: knowledge bonus value per level per category
export const KNOWLEDGE_CAT_VALUE = [20, 2, 0.1, 10, 3, 0.05, 1, 2, 0.2, 0.2, 100];

// Research[36]: Ring of Glory bonus descriptions
export const ROG_DESC = [
  '}x multiplier to Research EXP gain!',
  'All Minehead upgrades are {% cheaper',
  '+{ daily rolls for new Observations',
  '+{ Research Points',
  '+{% Research AFK gains',
  '+{ play at event games, FOREVER!',
  'All Spelunk Shop upgrades are {% cheaper',
  '}x artifact find chance',
  '+{ new magnifier',
  'All Summoning upgrades are {% cheaper',
  'All breeding Mobs deal }x damage',
  '}x Stamina Regen',
  '}x Minehead currency',
  '+{ Research Point',
  '{% chance ribbon +1 tier',
  '}x Class EXP gain',
  'Minehead upgrades now {% cheaper (replaces 30%)',
  'Exalted Stamps +0.01x bonus',
  '}x coins from monsters',
  '+{ Legend Talent Point',
  '}x Spelunking POW',
  '+{% grand discovery chance/LV',
  'Unlocks new Atom (Bucks)',
  'Prisma Bubbles +0.01x bonus',
  '+{% Research AFK gains',
  '}x Burger',
  'Sushi upgrades {% cheaper',
  'Spelunk Shop now {% cheaper (replaces 30%)',
  '}x Amber from Spelunking',
  '}x bits from Gaming',
  '+{ max Observation roll',
  '}x Rat King crown odds',
  '}x Stealth for Ninja Twins',
  '+{ Exotic Market purchases/week',
  'Summoning upgrades now {% cheaper (replaces 25%)',
  '}x farming Evo chance',
  '+{% Hat Rack multi',
  '}x coins from monsters',
  'Upgrade Vault upgrades {% cheaper',
  '}x Bubba Meat Slice',
  '+{ Tiny Cogs/day',
  '}x Sigil EXP',
  '}x Palette Luck',
  '}x Lab EXP gain',
  'Sushi upgrades now {% cheaper (replaces 25%)',
  'Sailing Captains }x more personal EXP',
  '}x Divinity PTS',
  'Upgrade Vault upgrades now {% cheaper (replaces 25%)',
  '}x Drop Rate',
  '}x Total DMG',
  'Nothing yet', 'Nothing yet', 'Nothing yet', 'Nothing yet',
];

// Research[37]: Ring of Glory bonus quantities
export const ROG_VALUES = [100,30,2,2,2,1,30,50,1,30,100,25,50,1,25,30,60,1,20,1,200,3,1,1,2,30,25,50,150,100,1,50,100,4,50,300,1,40,25,200,1,100,25,50,50,50,30,50,10,10,0,0,0,0];

// CurrencyPerTier lookup (from game source)
export const CURRENCY_PER_TIER = [1,3,8,20,50,115,250,560,1220,2650];
// for tier >= 10 and < 16: Math.pow(2.46 - tier/100, tier) + 5*tier + tier^2
// for tier >= 16: Math.pow(2.31, tier)

export function currencyPerTier(tier) {
  if (tier < 10) return CURRENCY_PER_TIER[tier] || 0;
  if (tier < 16) return Math.pow(2.46 - tier / 100, tier) + 5 * tier + Math.pow(tier, 2);
  return Math.pow(2.31, tier);
}

// FuelCost per tier of sushi being cooked
export function fuelCostPerTier(tier) {
  if (tier === 5) return 176;
  return 10 * Math.pow(1.83, tier) - Math.pow(tier, 2);
}

export const MAX_SLOTS = 120;
export const MAX_TIER = 53;
